version: '3.8'

services:
  predictionofgd:
    container_name: prediction_diabetes
    image: predictionofgd
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
